# Generated by Django 3.2.7 on 2021-09-19 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('short_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('code', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'verbose_name': 'Nazione',
                'verbose_name_plural': 'Nazioni',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('short_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('code', models.CharField(blank=True, max_length=2000, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generic.country')),
            ],
            options={
                'verbose_name': 'Province',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('short_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('code', models.CharField(blank=True, max_length=2000, null=True)),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generic.province')),
            ],
            options={
                'verbose_name': 'Città',
                'verbose_name_plural': 'Città',
            },
        ),
    ]
