# Generated by Django 3.2.7 on 2021-09-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_logger', '0003_auto_20191204_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webrequest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
