# Generated by Django 3.2.7 on 2022-02-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeepAffexPoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('signal_key', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('signal_name', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('signal_description', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('signal_config', models.CharField(blank=True, choices=[('ALGORITHM', 'ALGORITHM'), ('MODEL', 'MODEL'), ('SOURCE', 'SOURCE'), ('CLASSIFIER', 'CLASSIFIER')], default='', max_length=32, null=True)),
                ('signal_unit', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('multiplier', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
