# Generated by Django 3.2.7 on 2022-02-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfx', '0002_alter_deepaffexpoint_signal_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='deepaffexpoint',
            name='is_measure',
            field=models.BooleanField(default=True),
        ),
    ]
