# Generated by Django 3.2.7 on 2021-09-25 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriageCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, choices=[('WHITE', 'WHITE'), ('GREEN', 'GREEN'), ('YELLOW', 'YELLOW')], max_length=32, null=True)),
            ],
            options={
                'verbose_name': 'Codice triage',
                'verbose_name_plural': 'Codici triage',
            },
        ),
        migrations.CreateModel(
            name='TriageAccessReason',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triage.hospital')),
                ('related_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triage.triagecode')),
            ],
            options={
                'verbose_name': 'Motivo accesso',
                'verbose_name_plural': 'Motivi accesso al pronto soccorso',
            },
        ),
        migrations.CreateModel(
            name='TriageAccess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('access_date', models.DateTimeField(blank=True, null=True)),
                ('access_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triage.triageaccessreason')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='triage.hospital')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='triage.patient')),
                ('triage_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triage.triagecode')),
            ],
            options={
                'verbose_name': 'Accesso',
                'verbose_name_plural': 'Accessi al pronto soccorso',
            },
        ),
    ]
