# Generated by Django 3.2.7 on 2021-10-07 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0002_triageaccess_triageaccessreason_triagecode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVideo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video', models.FileField(blank=True, null=True, upload_to='patient_video')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triage.patient')),
                ('triage_access', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triage.triageaccess')),
            ],
            options={
                'verbose_name': 'Video Misura',
                'verbose_name_plural': 'Video Misura',
            },
        ),
    ]
