# Generated by Django 3.2.7 on 2021-10-10 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0004_alter_patientvideo_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientvideo',
            name='patient',
        ),
    ]
