# Generated by Django 3.2.7 on 2021-10-30 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0005_remove_patientvideo_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMeasureResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.TextField(blank=True, default='{}', null=True)),
                ('patient_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triage.patientvideo')),
            ],
            options={
                'verbose_name': 'Esito misurazioni',
                'verbose_name_plural': 'Esiti misurazioni',
            },
        ),
    ]
