# Generated by Django 3.2.7 on 2021-11-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0006_patientmeasureresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmeasureresult',
            name='measurement_id',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
