# Generated by Django 3.2.7 on 2021-11-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0007_patientmeasureresult_measurement_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='birth_place',
            new_name='birth_place_city',
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_place_province',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
