# Generated by Django 3.2.7 on 2021-11-06 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0001_initial'),
        ('triage', '0008_auto_20211103_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='triageaccess',
            name='exit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hospital_city', to='generic.city'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hospital_country', to='generic.country'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hospital_province', to='generic.province'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='domicile_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='domicile_city', to='generic.city'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='domicile_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='domicile_country', to='generic.country'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='domicile_province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='domicile_province', to='generic.province'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='triage.hospital'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='residence_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='residence_city', to='generic.city'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='residence_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='residence_country', to='generic.country'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='residence_province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='residence_province', to='generic.province'),
        ),
        migrations.AlterField(
            model_name='triageaccess',
            name='access_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='triage.triageaccessreason'),
        ),
        migrations.AlterField(
            model_name='triageaccess',
            name='triage_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='triage.triagecode'),
        ),
        migrations.AlterField(
            model_name='triageaccessreason',
            name='related_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='triage.triagecode'),
        ),
    ]
