# Generated by Django 3.2.7 on 2021-11-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0009_auto_20211107_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmeasureresult',
            name='measure_short',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
