# Generated by Django 3.2.7 on 2021-12-11 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0010_patientmeasureresult_measure_short'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureLogger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('log', models.TextField(blank=True, null=True)),
                ('triage_access', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triage.triageaccess')),
            ],
            options={
                'verbose_name': 'Log Misurazione',
                'verbose_name_plural': 'Logs Misurazioni',
            },
        ),
    ]
