# Generated by Django 3.2.7 on 2021-12-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_appgroup'),
        ('triage', '0012_measurelogger_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='app_groups',
            field=models.ManyToManyField(blank=True, to='app.AppGroup', verbose_name="Hospital's Application Groups"),
        ),
    ]
