# Generated by Django 3.2.7 on 2021-12-12 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0013_hospital_app_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='app_groups',
        ),
    ]
