# Generated by Django 3.2.7 on 2021-12-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0014_remove_hospital_app_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo'),
        ),
    ]
