# Generated by Django 3.2.7 on 2021-12-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0015_hospital_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='triage/hospital/logos', verbose_name='Logo'),
        ),
    ]
