# Generated by Django 3.2.7 on 2021-12-22 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0016_alter_hospital_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Totem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Nome')),
                ('code', models.UUIDField(blank=True, null=True, unique=True, verbose_name='Codice totem fisico')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrizione')),
                ('logs', models.TextField(blank=True, null=True, verbose_name='Storico')),
                ('working', models.BooleanField(default=True, verbose_name='Funzionante')),
                ('activation_date', models.DateTimeField(blank=True, null=True, verbose_name='Data di attivazione')),
                ('disposal_date', models.DateTimeField(blank=True, null=True, verbose_name='Data di dismissione')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data di creazione')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Data di creazione')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='triage.hospital')),
            ],
        ),
        migrations.AddField(
            model_name='triageaccess',
            name='totem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='triage.totem'),
        ),
    ]
