# Generated by Django 3.2.7 on 2021-12-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0017_auto_20211222_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totem',
            name='code',
            field=models.UUIDField(auto_created=True, blank=True, null=True, unique=True, verbose_name='Codice totem fisico'),
        ),
    ]
