# Generated by Django 3.2.7 on 2021-12-23 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0018_alter_totem_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
    ]
