# Generated by Django 3.2.7 on 2022-03-12 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0020_triageaccess__status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclaredAnagrafica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name='Anno di nascita')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Maschio'), ('female', 'Femmina')], max_length=31, null=True, verbose_name='Sesso')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Altezza')),
                ('weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='Peso')),
                ('smoking', models.BooleanField(blank=True, null=True, verbose_name='Fumatore')),
                ('diabetes', models.BooleanField(blank=True, null=True, verbose_name='Diabetico')),
                ('bloodpressuremedication', models.BooleanField(blank=True, null=True, verbose_name='Assume antipertensivi')),
                ('expired', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data di creazione')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Data di creazione')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triage.patient')),
            ],
        ),
    ]
