# Generated by Django 3.2.7 on 2022-03-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0021_declaredanagrafica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaredanagrafica',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
