# Generated by Django 3.2.7 on 2022-03-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0022_alter_declaredanagrafica_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaredanagrafica',
            name='bloodpressuremedication',
            field=models.BooleanField(blank=True, default=False, verbose_name='Assume antipertensivi'),
        ),
        migrations.AlterField(
            model_name='declaredanagrafica',
            name='diabetes',
            field=models.BooleanField(blank=True, default=False, verbose_name='Diabetico'),
        ),
        migrations.AlterField(
            model_name='declaredanagrafica',
            name='smoking',
            field=models.BooleanField(blank=True, default=False, verbose_name='Fumatore'),
        ),
    ]
