# Generated by Django 3.2.7 on 2022-04-02 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0023_auto_20220312_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triageaccess',
            name='access_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triage.triageaccessreason'),
        ),
    ]
