# Generated by Django 3.2.7 on 2022-04-02 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0024_alter_triageaccess_access_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='declaredanagrafica',
            options={'verbose_name': 'Demografica - DeepAffex', 'verbose_name_plural': 'Demografiche'},
        ),
    ]
