# Generated by Django 3.2.7 on 2022-04-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0025_alter_declaredanagrafica_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='triageaccessreason',
            name='order',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
