# Generated by Django 3.2.7 on 2022-11-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0026_triageaccessreason_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaredanagrafica',
            name='is_allergic',
            field=models.BooleanField(blank=True, default=False, verbose_name='Allergico ai pollini'),
        ),
        migrations.AddField(
            model_name='declaredanagrafica',
            name='is_asthmatic',
            field=models.BooleanField(blank=True, default=False, verbose_name='Asmatico'),
        ),
        migrations.AddField(
            model_name='declaredanagrafica',
            name='is_bloodpressure',
            field=models.BooleanField(blank=True, default=False, verbose_name='Iperteso'),
        ),
    ]
