# Generated by Django 3.2.7 on 2022-12-10 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0027_auto_20221121_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmeasureresult',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='triage.patient'),
        ),
    ]
