# Generated by Django 3.2.7 on 2021-12-08 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211208_0013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'verbose_name': 'Application User', 'verbose_name_plural': 'Application Users'},
        ),
    ]
