# Generated by Django 3.2.7 on 2021-12-12 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('app', '0005_auto_20211212_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='appgroups',
            field=models.ManyToManyField(blank=True, help_text='The application groups this user belongs to. A user will get all permissions granted to each of their application groups.', related_name='appuser_set', related_query_name='appuser', to='app.AppGroup', verbose_name='Application Groups'),
        ),
        migrations.AlterField(
            model_name='appgroup',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='appgroup',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
