# Generated by Django 3.2.7 on 2021-12-12 16:46

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0006_auto_20211212_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='appgroups',
        ),
        migrations.DeleteModel(
            name='AppGroup',
        ),
        migrations.CreateModel(
            name='AppGroup',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
