# Generated by Django 3.2.7 on 2021-12-22 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0017_auto_20211222_1203'),
        ('app', '0008_appuser_hospital_logged'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='totem_logged',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triage.totem', verbose_name='Totem'),
        ),
    ]
