# Generated by Django 3.2.7 on 2021-12-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_appuser_totem_logged'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='app/appuser/imgs', verbose_name='Immagine del profilo'),
        ),
    ]
