# Generated by Django 3.2.7 on 2022-01-16 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0019_remove_patient_user'),
        ('app', '0011_auto_20211223_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='_has_accepted_tec',
            field=models.BooleanField(default=False, verbose_name='Ha accettato i termini e condizioni'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='_dashboard_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='triage.hospital', verbose_name='Ospedale attualmente loggato'),
        ),
    ]
