# Generated by Django 3.2.7 on 2022-04-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220116_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='use_card_reader',
            field=models.BooleanField(default=True, verbose_name='Usa lettore tessera'),
        ),
    ]
