"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from envparse import env
from django.urls import reverse_lazy

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MEDIA_ROOT = os.path.join(os.path.join(os.path.dirname(__file__),'..','media'))
STATIC_ROOT = os.path.join(BASE_DIR,'collected_static/')
MEDIA_URL = '/media/'
STATIC_URL = '/static/'
STATICFILES_DIRS = ( os.path.join(BASE_DIR,'static/'),)

THEME_BASE_DIR = os.path.join(BASE_DIR, 'themes', 'default')
THEME_STATIC_DIR = os.path.join(THEME_BASE_DIR, 'assets')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '#fv11b8#4433d8%k$!nl5t@vn+h!4nu5(%3hkk-(muvop78f!c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG',cast=bool,default=True)
#ALLOWED_HOSTS = ['127.0.0.1', 'localhost', os.getenv('DJANGO_ADDITIONAL_ALLOWED_HOST')]
ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    'corsheaders',
    'drf_yasg',
    
    'auditlog',
    'custom_logger',
    'custom_mail',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',

    'custom_logger.middlewares.CurrentUserMiddleware',
    'custom_logger.middlewares.ErrorMiddleware',
    'auditlog.middleware.AuditlogMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR +"/templates/",
            BASE_DIR +"/",
        ],
        'OPTIONS': {
            'loaders': [
                (
                    'django.template.loaders.cached.Loader', # Must be enabled in DEBUG
                 [
                    'django.template.loaders.filesystem.Loader',
                    'django.template.loaders.app_directories.Loader',
                ]
                ),
            ],
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.request',
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

SITE_ID=1

TEMPLATES[0]['DIRS'].insert(0,os.path.join(THEME_BASE_DIR,'templates'))

WSGI_APPLICATION = 'project.wsgi.application'

MEDIA_ROOT = os.path.join(os.path.join(os.path.dirname(__file__),'..','media'))
MEDIA_URL = '/media/'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

SQLITE_DB_NAME=os.path.join(BASE_DIR, 'db.sqlite3')
DB_ENGINE=env("DJANGO_DB_ENGINE", default='django.db.backends.postgresql')
DB_NAME=env("DJANGO_DB_NAME", default='django')

DATABASES = {
    'default': {
        'ENGINE': env("DB_ENGINE", default='django.db.backends.sqlite3'),
        'NAME': env("DB_NAME", default=os.path.join(BASE_DIR, 'db.sqlite3') ),
        'USER': env("DB_USER", default=''),
        'PASSWORD': env("DB_PASSWORD", default=''),
        'HOST': env("DB_HOST", default=''),
        'PORT': env("DB_PORT", default=''),
        'TEST': {
            'NAME': 'testdb',
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

if DEBUG:
    TEMPLATES[0]['OPTIONS']['loaders'] = [
    'django.template.loaders.filesystem.Loader',
    'django.template.loaders.app_directories.Loader',
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

#LANGUAGE_CODE = 'en-us'
#TIME_ZONE = 'UTC'
#USE_I18N = True
#USE_L10N = True
#USE_TZ = True

LANGUAGE_CODE = 'it'
LANGUAGES = [
    ('it', 'Italiano'),
]
TIME_ZONE = 'Europe/Rome'
USE_I18N = True
USE_L10N = True
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR,'collected_static/')

EMAIL_BACKEND =  env("EMAIL_BACKEND",default='django.core.mail.backends.console.EmailBackend')
EMAIL_USE_SSL = env("EMAIL_USE_SSL",cast=bool, default=False)
EMAIL_HOST = env("EMAIL_HOST",default='in-v3.mailjet.com')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD',default='10dc0492db2d33cf0e52ddd20c820d31')
EMAIL_HOST_USER = env('EMAIL_HOST_USER',default='4424b623c674a1da4a072384c9c58648')
EMAIL_PORT =  env('EMAIL_PORT',cast=int,default=587)
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL",default='noreply@project.cloud')
DEBUG_EMAIL = env("DEBUG_EMAIL",cast=bool, default=True)

CORS_ORIGIN_ALLOW_ALL = True

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
)

DEBUG_PERFORMANCE= env("DEBUG_PERFORMANCE",cast=bool, default=False)
if DEBUG_PERFORMANCE:
    INSTALLED_APPS += ['debug_toolbar', 'silk']
    INTERNAL_IPS = ['127.0.0.1']
    MIDDLEWARE += ['debug_toolbar.middleware.DebugToolbarMiddleware']
    MIDDLEWARE.append('silk.middleware.SilkyMiddleware')

    DEBUG_TOOLBAR_PANELS = [
        'debug_toolbar.panels.versions.VersionsPanel',
        'debug_toolbar.panels.timer.TimerPanel',
        'debug_toolbar.panels.settings.SettingsPanel',
        'debug_toolbar.panels.headers.HeadersPanel',
        'debug_toolbar.panels.request.RequestPanel',
        'debug_toolbar.panels.sql.SQLPanel',
        'debug_toolbar.panels.staticfiles.StaticFilesPanel',
        'debug_toolbar.panels.templates.TemplatesPanel',
        'debug_toolbar.panels.cache.CachePanel',
        'debug_toolbar.panels.signals.SignalsPanel',
        'debug_toolbar.panels.logging.LoggingPanel',
        'debug_toolbar.panels.redirects.RedirectsPanel',
        'debug_toolbar.panels.profiling.ProfilingPanel',
    ]
