# Generated by Django 3.2.7 on 2022-10-15 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('triage', '0026_triageaccessreason_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data di creazione')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Data di modifica')),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('camera_rotation', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (90, '90'), (-90, '-90'), (180, '180')], default=0, null=True, verbose_name='Rotazione Camera')),
                ('red_value', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Canale R')),
                ('blue_value', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Canale B')),
                ('green_value', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Canale G')),
                ('color', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Colore')),
                ('contrast', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Contrasto')),
                ('brightness', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Luminosita')),
                ('sharpness', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Nitidezza')),
                ('totem', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='triage.totem')),
            ],
            options={
                'verbose_name': 'Impostazione video',
                'verbose_name_plural': 'Impostazioni video',
            },
        ),
    ]
