# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-13 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name=b'Mail ID')),
                ('sent', models.BooleanField(default=False, verbose_name=b'Has sent email')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name=b'Data of send request')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name=b'Data of effective send')),
                ('retry', models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of retry')),
                ('reply_to', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reply to')),
                ('to_who', models.TextField(blank=True, null=True, verbose_name='To separated with ; ')),
                ('cc_who', models.TextField(blank=True, null=True, verbose_name='CC separated with ; ')),
                ('bcc_who', models.TextField(blank=True, null=True, verbose_name='BCC separated with ; ')),
                ('subject', models.TextField(blank=True, null=True, verbose_name='Subject')),
                ('json_message', models.TextField(blank=True, null=True, verbose_name='JSON Message')),
                ('template_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Template name')),
                ('attachments', models.TextField(blank=True, null=True, verbose_name='Attachments separated with ; ')),
            ],
            options={
                'verbose_name': 'Mail',
                'verbose_name_plural': 'Mails',
            },
        ),
    ]
