# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-15 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
