# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-18 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_mail', '0002_mail_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='html_text',
            field=models.TextField(blank=True, null=True, verbose_name='Html Text'),
        ),
        migrations.AddField(
            model_name='mail',
            name='txt_text',
            field=models.TextField(blank=True, null=True, verbose_name='Txt Text'),
        ),
    ]
