# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-04 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_mail', '0003_auto_20190718_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data of effective send'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Mail ID'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data of send request'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='sent',
            field=models.BooleanField(default=False, verbose_name='Has sent email'),
        ),
    ]
