# Generated by Django 3.0.2 on 2020-01-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_auto_20191204_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='from_who',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='From'),
        ),
    ]
