# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-13 16:25
from __future__ import unicode_literals

import logger.middlewares
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False, verbose_name=b'Log ID')),
                ('level', models.IntegerField(blank=True, choices=[(1, b'DEBUG'), (2, b'INFO'), (3, b'WARNING'), (4, b'ERROR'), (5, b'CRITICAL')], null=True, verbose_name='logger level')),
                ('entity', models.CharField(blank=True, max_length=255, null=True, verbose_name='Entity')),
                ('entity_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Entity id')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name=b'Data')),
                ('request', models.TextField(blank=True, null=True, verbose_name='Request')),
                ('exception', models.TextField(blank=True, null=True, verbose_name='Exception')),
                ('custom_message', models.TextField(blank=True, null=True, verbose_name='Logging message')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
        migrations.CreateModel(
            name='LoggerMessage',
            fields=[
                ('log_message_id', models.IntegerField(primary_key=True, serialize=False, verbose_name=b'Log message ID')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Logging message')),
            ],
            options={
                'verbose_name': 'Log message',
                'verbose_name_plural': 'Log messages',
            },
        ),
        migrations.CreateModel(
            name='WebRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('host', models.CharField(max_length=1000)),
                ('path', models.CharField(max_length=1000)),
                ('method', models.CharField(max_length=50)),
                ('uri', models.CharField(max_length=2000)),
                ('user_agent', models.CharField(blank=True, max_length=1000, null=True)),
                ('remote_addr', models.GenericIPAddressField()),
                ('remote_addr_fwd', models.GenericIPAddressField(blank=True, null=True)),
                ('meta', models.TextField()),
                ('cookies', models.TextField(blank=True, null=True)),
                ('get', models.TextField(blank=True, null=True)),
                ('post', models.TextField(blank=True, null=True)),
                ('is_secure', models.BooleanField()),
                ('is_ajax', models.BooleanField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Web request',
                'verbose_name_plural': 'Web requests',
            },
        ),
        migrations.AddField(
            model_name='logger',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesasge', to='logger.LoggerMessage'),
        ),
        migrations.AddField(
            model_name='logger',
            name='user',
            field=models.ForeignKey(blank=True, default=logger.middlewares.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'User'),
        ),
        migrations.AddField(
            model_name='logger',
            name='web_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='web_request', to='logger.WebRequest'),
        ),
    ]
