# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    def setup_logs(apps, schema_editor):
        LoggerMessage = apps.get_model("logger", "LoggerMessage")
        LoggerMessage.objects.get_or_create(log_message_id=1,message='Error')
        LoggerMessage.objects.get_or_create(log_message_id=2,message='Login complete')
        LoggerMessage.objects.get_or_create(log_message_id=3,message='User is not active')
        LoggerMessage.objects.get_or_create(log_message_id=4,message='Username or password are not correct')
        LoggerMessage.objects.get_or_create(log_message_id=6,message='Try to login...')
        LoggerMessage.objects.get_or_create(log_message_id=7,message='Logout complete')
        LoggerMessage.objects.get_or_create(log_message_id=8,message='Import started')
        LoggerMessage.objects.get_or_create(log_message_id=9,message='Import confirmed')
        LoggerMessage.objects.get_or_create(log_message_id=10,message='Login Info')
        LoggerMessage.objects.get_or_create(log_message_id=11,message='Login GUID analisys')
    
    operations = [
        migrations.RunPython(setup_logs)
    ]
