# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-04 08:58
from __future__ import unicode_literals

import logger.middlewares
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_auto_20180917_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='logger',
            name='level',
            field=models.IntegerField(blank=True, choices=[(1, 'DEBUG'), (2, 'INFO'), (3, 'WARNING'), (4, 'ERROR'), (5, 'CRITICAL')], null=True, verbose_name='logger level'),
        ),
        migrations.AlterField(
            model_name='logger',
            name='log_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Log ID'),
        ),
        migrations.AlterField(
            model_name='logger',
            name='user',
            field=models.ForeignKey(blank=True, default=logger.middlewares.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='loggermessage',
            name='log_message_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Log message ID'),
        ),
    ]
